# Generated by Django 5.2.1 on 2025-05-11 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True, verbose_name='Texte du gage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Gage',
                'verbose_name_plural': 'Gages',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamertag', models.CharField(max_length=100, unique=True, verbose_name='Pseudo du joueur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Joueur',
                'verbose_name_plural': 'Joueurs',
            },
        ),
        migrations.CreateModel(
            name='MasterkillEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nouveau Masterkill', max_length=150, verbose_name='Nom du Masterkill')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('effective_start_at', models.DateTimeField(blank=True, null=True, verbose_name='Début effectif')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('points_kill', models.IntegerField(default=1, verbose_name='Points par Kill')),
                ('points_rea', models.IntegerField(default=1, verbose_name='Points par Réanimation')),
                ('points_redeploiement', models.IntegerField(default=-1, verbose_name='Points par Redéploiement utilisé')),
                ('points_goulag_win', models.IntegerField(default=1, verbose_name='Points par Goulag gagné')),
                ('points_rage_quit', models.IntegerField(default=-5, verbose_name='Points par Rage Quit')),
                ('points_execution', models.IntegerField(default=1, verbose_name='Points par Exécution')),
                ('points_humiliation', models.IntegerField(default=-1, verbose_name='Points par Humiliation subie')),
                ('num_games_planned', models.PositiveIntegerField(default=3, verbose_name='Nombre de parties prévues')),
                ('top1_solo_ends_mk', models.BooleanField(default=False, help_text='Un Top 1 solo met-il fin au Masterkill ?', verbose_name='Top 1 Solo termine le MK')),
                ('status', models.CharField(choices=[('pending', 'En attente de démarrage'), ('inprogress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_masterkills', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('selected_gage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gage', verbose_name='Gage sélectionné')),
                ('participants', models.ManyToManyField(blank=True, related_name='masterkill_events_participated', to='api.player', verbose_name='Participants')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masterkills_won', to='api.player', verbose_name='Vainqueur')),
            ],
            options={
                'verbose_name': 'Événement Masterkill',
                'verbose_name_plural': 'Événements Masterkill',
                'ordering': ['-created_at'],
            },
        ),
    ]
