# Generated by Django 5.2.1 on 2025-05-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterkillevent',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de démarrage'), ('inprogress', 'En cours'), ('paused', 'En Pause'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
