# Generated by Django 5.2.1 on 2025-07-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_game_squad_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='has_auto_stats',
            field=models.BooleanField(default=False, verbose_name='Stats auto-remplies'),
        ),
    ]
