# Generated by Django 5.2.1 on 2025-05-11 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_masterkillevent_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gage',
            options={'ordering': ['text'], 'verbose_name': 'Gage', 'verbose_name_plural': 'Gages'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['gamertag'], 'verbose_name': 'Joueur', 'verbose_name_plural': 'Joueurs'},
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.PositiveIntegerField(verbose_name='Numéro de la partie')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('inprogress', 'En cours'), ('completed', 'Terminée')], default='pending', max_length=15, verbose_name='Statut de la partie')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Début de la partie')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin de la partie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('masterkill_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='api.masterkillevent', verbose_name='Événement Masterkill')),
            ],
            options={
                'verbose_name': 'Partie',
                'verbose_name_plural': 'Parties',
                'ordering': ['masterkill_event', 'game_number'],
                'unique_together': {('masterkill_event', 'game_number')},
            },
        ),
        migrations.CreateModel(
            name='GamePlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.PositiveIntegerField(default=0, verbose_name='Kills')),
                ('deaths', models.PositiveIntegerField(default=0, verbose_name='Morts')),
                ('assists', models.PositiveIntegerField(default=0, verbose_name='Assistances')),
                ('revives_done', models.PositiveIntegerField(default=0, verbose_name='Réanimations effectuées')),
                ('gulag_wins', models.PositiveIntegerField(default=0, verbose_name='Goulags gagnés')),
                ('times_executed_enemy', models.PositiveIntegerField(default=0, verbose_name='Exécutions sur ennemi')),
                ('times_got_executed', models.PositiveIntegerField(default=0, verbose_name='Exécutions subies')),
                ('rage_quit', models.BooleanField(default=False, verbose_name='A quitté en cours (Rage Quit)')),
                ('score_in_game', models.IntegerField(default=0, verbose_name='Score pour cette partie')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='api.game', verbose_name='Partie')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='api.player', verbose_name='Joueur')),
            ],
            options={
                'verbose_name': 'Statistique Joueur par Partie',
                'verbose_name_plural': 'Statistiques Joueurs par Partie',
                'unique_together': {('game', 'player')},
            },
        ),
    ]
