# Generated by Django 5.2.1 on 2025-05-11 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_gage_options_alter_player_options_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayerstats',
            name='times_redeployed_by_teammate',
            field=models.PositiveIntegerField(default=0, verbose_name='Redéployé par coéquipier'),
        ),
        migrations.AlterField(
            model_name='masterkillevent',
            name='points_redeploiement',
            field=models.IntegerField(default=-1, verbose_name='Points par Redéploiement'),
        ),
        migrations.AlterField(
            model_name='masterkillevent',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('inprogress', 'En cours'), ('paused', 'En Pause'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='masterkillevent',
            name='top1_solo_ends_mk',
            field=models.BooleanField(default=False, help_text='Un Top 1 solo met fin au MK ?', verbose_name='Top 1 Solo termine le MK'),
        ),
        migrations.CreateModel(
            name='RedeployEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeploy_events', to='api.game', verbose_name='Partie Concernée')),
                ('redeployed_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='was_redeployed_by_log', to='api.player', verbose_name='Joueur redéployé')),
                ('redeployer_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_redeploys', to='api.player', verbose_name='Joueur qui redéploie')),
            ],
            options={
                'verbose_name': 'Événement de Redéploiement',
                'verbose_name_plural': 'Événements de Redéploiement',
                'ordering': ['-timestamp'],
            },
        ),
    ]
