# Generated by Django 5.2.1 on 2025-05-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gameplayerstats_times_redeployed_by_teammate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayerstats',
            name='gulag_wins',
        ),
        migrations.AddField(
            model_name='gameplayerstats',
            name='gulag_won',
            field=models.BooleanField(default=False, verbose_name='Goulag Gagné'),
        ),
    ]
