# Generated by Django 5.2.1 on 2025-05-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_gameplayerstats_gulag_wins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayerstats',
            name='gulag_won',
        ),
        migrations.AddField(
            model_name='gameplayerstats',
            name='gulag_status',
            field=models.CharField(choices=[('not_played', 'Non Joué / Fermé'), ('won', 'Gagné'), ('lost', 'Perdu')], default='not_played', max_length=10, verbose_name='Résultat Goulag'),
        ),
    ]
