# Generated by Django 5.2.1 on 2025-05-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_gameplayerstats_gulag_won_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayerstats',
            name='gulag_status',
            field=models.CharField(choices=[('not_played', 'Fermeture'), ('won', 'Gagné'), ('lost', 'Perdu')], default='not_played', max_length=10, verbose_name='Résultat Goulag'),
        ),
    ]
