# Generated by Django 5.2.1 on 2025-05-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_gameplayerstats_gulag_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='kill_multiplier',
            field=models.FloatField(default=1.0, verbose_name='Multiplicateur de Kills'),
        ),
        migrations.AddField(
            model_name='masterkillevent',
            name='has_bonus_reel',
            field=models.BooleanField(default=True, verbose_name='Roue des Bonus activée'),
        ),
        migrations.AddField(
            model_name='masterkillevent',
            name='has_kill_multipliers',
            field=models.BooleanField(default=False, verbose_name='Multiplicateurs de Kills activés'),
        ),
    ]
