# Generated by Django 5.2.1 on 2025-05-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_game_kill_multiplier_masterkillevent_has_bonus_reel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='spawn_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de Spawn'),
        ),
    ]
