# Generated by Django 5.2.1 on 2025-05-16 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_game_spawn_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revive_events', to='api.game', verbose_name='Partie Concernée')),
                ('revived_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='was_revived_events', to='api.player', verbose_name='Joueur réanimé')),
                ('reviver_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revives_performed', to='api.player', verbose_name='Joueur qui réanime')),
            ],
            options={
                'verbose_name': 'Événement de Réanimation',
                'verbose_name_plural': 'Événements de Réanimation',
                'ordering': ['-timestamp'],
            },
        ),
    ]
